require:
  - rubocop-rails

inherit_mode:
  merge: Exclude

Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Bundler/GemFilename:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/LineLength:
  Enabled: false

Lint/SuppressedException:
  AllowComments: true

Metrics/AbcSize:
  AllowedMethods: [ 'included' ]
Metrics/BlockLength:
  CountAsOne: [ 'array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - "**/patches/**/*"
    - "**/easy_patch/**/*"
    - "**/spec/**/*"
Metrics/ClassLength:
  CountAsOne: [ 'array', 'hash', 'heredoc', 'method_call']
Metrics/CyclomaticComplexity:
  AllowedMethods:
    - included
Metrics/MethodLength:
  CountAsOne: [ 'array', 'hash', 'heredoc', 'method_call']
  AllowedMethods: [ 'included' ]
Metrics/ModuleLength:
  CountAsOne: [ 'array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - "**/patches/**/*"
    - "**/easy_patch/**/*"
Metrics/PerceivedComplexity:
  AllowedMethods:
    - included

Naming/BlockForwarding:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/ApplicationRecord:
  Enabled: false
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/IfUnlessModifier:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/QuotedSymbols:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
