name: Lint
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3.7"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
